### ISSUE TITLE
Configure footer size in mobile view

### ISSUE THREAD

**Issue by LyndonTomas** [iflexhibit/iflexhibit#18]
One must configure the size of the footer in mobile view.

**Comment by jp-ong** [comment]
**Quick tips and reminders**

- Make sure to document your changes when you submit a pull request.
- Assign reviewers, assignees, projects, and linked issue in your pull requests.
- CSS color values and fonts are all in the file `src/styles/global.scss`.

**Sample usage:**
_You may add variables if you want_
```
:root{
  --black: #000000;
  --sans: 'Roboto', sans-serif;
}

body{
  background-color: var(--black);
  font-family: var(--sans);
}
```

**Comment by jp-ong** [comment]
Will reopen when ready.
