### ISSUE TITLE
Configure: NavBar size in Mobile View

### ISSUE THREAD

**Issue by nikkieyabut** [iflexhibit/iflexhibit#19]
Resize navbar

**Comment by jp-ong** [comment]
**Quick tips and reminders**

- Make sure to document your changes when you submit a pull request.
- Assign reviewers, assignees, projects, and linked issue in your pull requests.
- CSS color values and fonts are all in the file `src/styles/global.scss`.

**Sample usage:**
_You may add variables if you want_
```
:root{
  --black: #000000;
  --sans: 'Roboto', sans-serif;
}

body{
  background-color: var(--black);
  font-family: var(--sans);
}
```

**Comment by nikkieyabut** [comment]
> **Quick tips and reminders**
> 
> * Make sure to document your changes when you submit a pull request.
> * Assign reviewers, assignees, projects, and linked issue in your pull requests.
> * CSS color values and fonts are all in the file `src/styles/global.scss`.
> 
> **Sample usage:**
> _You may add variables if you want_
> 
> ```
> :root{
>   --black: #000000;
>   --sans: 'Roboto', sans-serif;
> }
> 
> body{
>   background-color: var(--black);
>   font-family: var(--sans);
> }
> ```

thanks for reminding me lowds!!

**Comment by jp-ong** [comment]
Will reopen when ready.
